# 数据配置
data:
  data_path: "Data/averaged_data.csv"
  features:
    - "PPFD"
    - "CO2"
    - "T"
    - "R:B"
  target: "Pn_avg"
  test_size: 0.2
  random_state: 42
  normalize_method: "standard"

# 模型配置
model:
  model_type: "GPR"
  kernel: "rbf"
  C: 1.0
  gamma: 0.5
  sigma2: 0.5
  alpha: 1.0e-6
  n_restarts_optimizer: 5
  length_scale: 1.0
  constant_value: 1.0
  noise_level: 1.0e-6
  n_layers: 2
  dgp_alpha: 1.0e-6

# 优化配置
optimization:
  optimizer_type: "TPE"
  population_size: 10
  generations: 20
  crossover_rate: 0.4
  mutation_rate: 0.01
  tournament_size: 3
  n_particles: 10
  n_iterations: 20
  w: 1.0
  c1: 2.0
  c2: 2.0
  n_trials: 20
  n_butterflies: 10
  sensory_modality: 0.01
  power_exponent: 0.1
  switch_probability: 0.8
  cmaes_population_size: 10
  cmaes_sigma0: 0.3
  cmaes_seed: 42
  param_bounds:
    C: [0.1, 100]
    gamma: [0.1, 10.0]
    sigma2: [0.1, 100]
    alpha: [1e-8, 1.0]
    length_scale: [1e-2, 1e2]
    constant_value: [1e-2, 1e2]
    noise_level: [1e-8, 1.0]
    n_restarts_optimizer: [5, 20]
    n_layers: [1, 4]
    dgp_alpha: [1e-8, 1.0]

# 评估配置
evaluation:
  cv_folds: 3
  n_jobs: -1
  metrics:
    - "rmse"
    - "r2"
    - "mae"
    - "mean_std"
    - "max_std"
  plot_size: [12, 8]
  save_plots: true
  plot_format: "png"

# 实验配置
experiment:
  name: "photosynthesis_prediction"
  results_dir: "results"
  models_dir: "models"
  log_level: "INFO"
  log_file: "experiment.log" 