# 集成优化流程系统配置文件

general:
  output_dir: "integrated_workflow/results"
  log_level: "INFO"
  enable_checkpoints: true
  checkpoint_frequency: 1  # 每个阶段结束后

ml_training:
  framework_path: "ML_Framework"
  script_path: "run_experiment.py"
  config_file: "config/gpr_cmaes_config.yaml"
  model_type: "LSSVR"  # 可选: LSSVR, GPR, SVR
  test_size: 0.2
  random_state: 42

optimization:
  framework_path: "pymoo"
  script_path: "find_optimal_conditions_multi_model.py"
  config_file: "moo_optimization_config.yaml"
  algorithm: "NSGA2"  # 可选: NSGA2, SPEA2
  population_size: 100
  generations: 200
  variables:
    ppfd:
      lower_bound: 100
      upper_bound: 1000
    r_b_ratio:
      lower_bound: 0.5
      upper_bound: 4.0
    temperature:
      lower_bound: 15
      upper_bound: 35
  objectives:
    - maximize_photosynthesis
    - minimize_cled_cost

optimal_point:
  framework_path: "Optimal"
  script_path: "fit.py"
  fitting_method: "polynomial"  # 可选: polynomial, spline
  polynomial_degree: 3
  visualization:
    enable: true
    format: "png"
    dpi: 300

mpc_simulation:
  framework_path: "mpc-farming-master"
  script_path: "mpc.py"
  simulation_duration: 24  # 小时
  time_step: 0.1  # 小时
  control_horizon: 6  # 步数
  prediction_horizon: 12  # 步数
  constraints:
    ppfd:
      min: 0
      max: 1000
    temperature:
      min: 15
      max: 35